// react-poc/src/components/auth/SignIn.tsx
import React, { useState } from 'react';
import Account from '../../services/Account';
import { InputField, InputButton } from '../Inputs';
import AuthProps from './AuthProps';
import "../../stylesheets/Connection.css";

const SignIn: React.FC<AuthProps> = ({ updateSignIn, setConnected }: AuthProps) => {
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');

    const changeEmail = (e: React.ChangeEvent<HTMLInputElement>): void => {
        setEmail(e.target.value);
    };

    const changePassword = (e: React.ChangeEvent<HTMLInputElement>): void => {
        setPassword(e.target.value);
    };

    const checkInputs = (): void => {
        if (!!email && !!password) {
            Account.login({
                email: email,
                password: password,
            }).then(res => {
                console.log(res);
                setConnected(true);
            }).catch(err => {
                console.error(err);
                setEmail('');
                setPassword('');
                setConnected(false);
            });
        } else {
            console.log('Impossible');
            setConnected(false);
        }
    };

    return (
        <div className="Connection">
            <h1>Sign In</h1>
            <InputField type="email" value={email}
                placeholder="Email" onChange={changeEmail} />
            <InputField type="password" value={password}
                placeholder="Password" onChange={changePassword} />
            <InputButton text="Sign In" onClick={checkInputs} />
            <InputButton text="I don't have an account" onClick={updateSignIn} />
        </div>
    );
};

export default SignIn;

// vue-poc/src/components/auth/SignIn.vue
<template>
    <div class="Connection">
        <h1>Sign In</h1>
        <InputField type="email" placeholder="Email" @changed="changeEmail" />
        <InputField type="password" placeholder="Password" @changed="changePassword" />
        <InputButton text="Sign In" @clicked="checkInputs" />
        <InputButton text="I don't have an account" @clicked="updateSignIn" />
    </div>
</template>

<script>
import Account from '../../services/Account'
import { InputField, InputButton } from '../Inputs'

export default {
    name: 'SignIn',
    components: { InputField, InputButton },
    data() {
        return {
            email: '',
            password: '',
        }
    },
    methods: {
        changeEmail(email) {
            this.email = email;
        },

        changePassword(password) {
            this.password = password;
        },

        updateSignIn() {
            this.$emit('updateSignIn');
        },

        checkInputs() {
            if (!!this.email && !!this.password) {
                Account.login({
                    email: this.email,
                    password: this.password,
                }).then(res => {
                    console.log(res);
                }).catch(err => {
                    console.error(err);
                });
            } else {
                console.log('Impossible');
            }
        }
    }
}
</script>

<style scoped>
.Connection {
    text-align: center;
    margin: 0 auto;
    margin-top: 12em;
    padding-top: 6em;
    height: 28em;
    width: 26em;
    border-radius: 120px;
    box-shadow: 0px 0px 120px 20px rgba(0,0,0,0.35);
}

.Connection button {
    margin-top: 1em;
    background-color: #d3d3d3;
    color: #424242;
    border: none;
    border-radius: 8px;
    padding: 12px 0px;
    width: 200px;
    text-decoration: none;
    display: inline-block;
}

.Connection button:hover {
    background-color: #424242;
    color: #d3d3d3;
}

.Connection input {
    margin-top: 1em;
    width: 200px;
}
</style>
